language: node_js
sudo: required
dist: trusty
node_js:
  - '8.9.1'

addons:
 chrome: stable

before_script:
- export CHROME_BIN=/usr/bin/google-chrome
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start

before_script:
- npm install -g angular-cli
- npm install -g karma
- npm install
- ng build

script: ng test --single-run
